"""empty message

Revision ID: 3a194c27a0eb
Revises: 82ed84c3c2d1
Create Date: 2018-11-29 15:03:56.296835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a194c27a0eb'
down_revision = '82ed84c3c2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_doctor_username'), 'doctor', ['username'], unique=True)
    op.add_column('patient', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_patient_username'), 'patient', ['username'], unique=True)
    op.add_column('pharmacist', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_pharmacist_username'), 'pharmacist', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pharmacist_username'), table_name='pharmacist')
    op.drop_column('pharmacist', 'username')
    op.drop_index(op.f('ix_patient_username'), table_name='patient')
    op.drop_column('patient', 'username')
    op.drop_index(op.f('ix_doctor_username'), table_name='doctor')
    op.drop_column('doctor', 'username')
    # ### end Alembic commands ###
