"""empty message

Revision ID: 82ed84c3c2d1
Revises: 
Create Date: 2018-11-29 08:55:27.410353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ed84c3c2d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('hospital', sa.String(length=96), nullable=True),
    sa.Column('medical_license', sa.String(length=96), nullable=True),
    sa.Column('street_address', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('zip_code', sa.String(length=12), nullable=True),
    sa.Column('country', sa.String(length=96), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=14), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_first_name'), 'doctor', ['first_name'], unique=False)
    op.create_index(op.f('ix_doctor_gender'), 'doctor', ['gender'], unique=False)
    op.create_index(op.f('ix_doctor_hospital'), 'doctor', ['hospital'], unique=False)
    op.create_index(op.f('ix_doctor_last_name'), 'doctor', ['last_name'], unique=False)
    op.create_index(op.f('ix_doctor_middle_name'), 'doctor', ['middle_name'], unique=False)
    op.create_table('pharmacist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('pharmacy', sa.String(length=96), nullable=True),
    sa.Column('medical_license', sa.String(length=96), nullable=True),
    sa.Column('street_address', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('zip_code', sa.String(length=12), nullable=True),
    sa.Column('country', sa.String(length=96), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=14), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacist_first_name'), 'pharmacist', ['first_name'], unique=False)
    op.create_index(op.f('ix_pharmacist_gender'), 'pharmacist', ['gender'], unique=False)
    op.create_index(op.f('ix_pharmacist_last_name'), 'pharmacist', ['last_name'], unique=False)
    op.create_index(op.f('ix_pharmacist_middle_name'), 'pharmacist', ['middle_name'], unique=False)
    op.create_index(op.f('ix_pharmacist_pharmacy'), 'pharmacist', ['pharmacy'], unique=False)
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=True),
    sa.Column('is_name_brand', sa.Boolean(), nullable=True),
    sa.Column('refills_left', sa.Integer(), nullable=True),
    sa.Column('directions', sa.String(length=300), nullable=True),
    sa.Column('disbursed', sa.Integer(), nullable=True),
    sa.Column('dosage_strength', sa.String(length=5), nullable=True),
    sa.Column('prescribe_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_name'), 'prescription', ['name'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('pharm_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('middle_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('primary_physician', sa.String(length=96), nullable=True),
    sa.Column('insurance_number', sa.String(length=64), nullable=True),
    sa.Column('street_address', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('zip_code', sa.String(length=12), nullable=True),
    sa.Column('country', sa.String(length=96), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=14), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['pharm_id'], ['pharmacist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_first_name'), 'patient', ['first_name'], unique=False)
    op.create_index(op.f('ix_patient_gender'), 'patient', ['gender'], unique=False)
    op.create_index(op.f('ix_patient_last_name'), 'patient', ['last_name'], unique=False)
    op.create_index(op.f('ix_patient_middle_name'), 'patient', ['middle_name'], unique=False)
    op.create_index(op.f('ix_patient_primary_physician'), 'patient', ['primary_physician'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_name'), 'allergies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allergies_name'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_patient_primary_physician'), table_name='patient')
    op.drop_index(op.f('ix_patient_middle_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_last_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_gender'), table_name='patient')
    op.drop_index(op.f('ix_patient_first_name'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_prescription_name'), table_name='prescription')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_pharmacist_pharmacy'), table_name='pharmacist')
    op.drop_index(op.f('ix_pharmacist_middle_name'), table_name='pharmacist')
    op.drop_index(op.f('ix_pharmacist_last_name'), table_name='pharmacist')
    op.drop_index(op.f('ix_pharmacist_gender'), table_name='pharmacist')
    op.drop_index(op.f('ix_pharmacist_first_name'), table_name='pharmacist')
    op.drop_table('pharmacist')
    op.drop_index(op.f('ix_doctor_middle_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_last_name'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_hospital'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_gender'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_first_name'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
